// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

/// A platform-specific Firebase configuration object.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CSF94Qh3sBmOaDKEgp-G5MIzxZaa04Y',
    appId: '1:316746655715:android:2a14b4d268c80811ed62d6',
    messagingSenderId: '316746655715',
    projectId: 'my-maeul-373c4',
    storageBucket: 'my-maeul-373c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfm7Y0nYy0nYy0nYy0nYy0nYy0nYy',
    appId: '1:123456789012:ios:1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'my-maeul-373c4',
    storageBucket: 'my-maeul-373c4.firebasestorage.app',
    iosClientId: '123456789012-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}